/**
 * Low open-PO alert: SKU x manufacturer pairs with little still on order.
 * Pure, so a unit test can import it.
 */

import { isoDate } from "@/lib/date"
import { escapeHtml, num, table, TITLE, MUTED, type Cell } from "./digest-html"

export const OPEN_QTY_THRESHOLD = 1500

export const STALE_DAYS = 14

export type RowState = "declining" | "stalled" | "never received"

/** Keyed on RowState, so a new status cannot ship without an explanation. */
const STATUS_NOTES: Record<RowState, string> = {
  declining: `Something was received in the last ${STALE_DAYS} days. The order is moving; the balance is simply running low.`,
  stalled: `Part of the order has arrived, but nothing in over ${STALE_DAYS} days. Worth chasing.`,
  "never received": "Nothing has ever been received against this order. Either it has not started or it has been forgotten.",
}

export type LowOpenRow = {
  sku_code: string
  sku_name: string | null
  mfg_code: string
  mfg_name: string
  open_qty: number
  open_pos: number
  earliest_expected: Date | string | null
  last_receipt_at: Date | string | null
}

/** Marked, never filtered: a stalled pair is the more urgent case, because
 *  nothing has arrived and nothing is arriving. */
export function classify(lastReceiptAt: Date | string | null, now: number): RowState {
  if (!lastReceiptAt) return "never received"
  const at = lastReceiptAt instanceof Date ? lastReceiptAt : new Date(lastReceiptAt)
  if (Number.isNaN(at.getTime())) return "never received"
  return now - at.getTime() > STALE_DAYS * 86_400_000 ? "stalled" : "declining"
}

/** Code on top, name beneath. Escaped here because `{ html }` bypasses table(). */
const twoLine = (code: string, name: string | null): Cell => ({
  html: `<div style="font-weight:600">${escapeHtml(code)}</div>` +
    (name ? `<div style="color:#888;font-size:12px">${escapeHtml(name)}</div>` : ""),
})

export function renderLowOpenPo(
  day: string,
  rows: (LowOpenRow & { state: RowState })[],
  threshold = OPEN_QTY_THRESHOLD
): string {
  return `
<div style="font-family:sans-serif;max-width:760px;margin:auto;color:#111;font-size:14px;line-height:1.5">
  <h2 style="margin:0 0 2px">Low open PO quantity</h2>
  <p style="${MUTED};margin-top:0">
    ${escapeHtml(day)} · ${num(rows.length)} ${rows.length === 1 ? "pair" : "pairs"}
    under ${num(threshold)} units still on order
  </p>

  ${table(
    ["SKU", "Manufacturer", "Open qty", "POs", "Earliest due", "Last receipt", "State"],
    rows.map((r) => [
      twoLine(r.sku_code, r.sku_name),
      twoLine(r.mfg_code, r.mfg_name),
      num(r.open_qty),
      num(r.open_pos),
      isoDate(r.earliest_expected) || "—",
      isoDate(r.last_receipt_at) || "never",
      r.state,
    ]),
    2
  )}

  <h3 style="${TITLE}">Status</h3>
  ${table(
    ["Status", "What it means"],
    Object.entries(STATUS_NOTES).map(([state, note]) => [state, note] as Cell[]),
    // Both columns are prose, so nothing is right-aligned.
    99
  )}

  <p style="font-size:12px;color:#888;margin-top:20px">
    Auto-generated by the mcaffeine ERP at 08:00 IST. To change who receives this,
    edit the <strong>report</strong> contacts under PO Procurement &rsaquo; Entity Emails.
  </p>
</div>`
}
